version: "3"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "6000:27017"
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data

volumes:
  mongodb:
  redisDB:
